name: rotas_rurais
description: "Aplicativo Rotas Rurais"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_database: ^12.0.1
  url_launcher: ^6.3.0
  open_location_code: ^1.0.1
  share_plus: ^10.0.2
  intl: ^0.19.0
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.14.0
  xml: ^6.5.0
  flutter_lints: ^5.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  connectivity_plus: ^6.0.5
  flutter_map_marker_cluster: ^1.3.6
  pdf: ^3.11.0
  printing: ^5.13.3

  proj4dart: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  xml: ^6.5.0
  flutter_lints: ^5.0.0



flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fundo.jpeg
    - assets/logo_semit.png
    - assets/estradas.geojson
    - assets/estradas.json
